config/routes.rb
Rails.application.routes.draw do

namespace :admin do
   resources :items
   resources :customers
   root to: "homes#top"
   resources :orders, only: [:show, :update]
   resources :genres
   resources :order_details, only: [:update]
  end


  devise_for :customers, skip: [:passwords] ,controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'

  }

  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

resources :items, only: [:show, :index], controller: "public/items"
resources :addresses, controller: "public/addresses"
resources :orders, controller: "public/orders" do
  collection do
    post 'confirm'
    get 'complete'
  end
end
resources :cart_items, controller: "public/cart_items" do
  collection do
    delete 'destroy_all'
  end
end

resource :customers, except: [:show], controller: "public/customers" do
  collection do
    get 'unsubscribe'
    get 'my_page' => "public/customers#show"
    patch "withdraw"
  end
end

get "about" => "public/homes#about"


  root to: "public/homes#top"






  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer, foreign_key: 'customer_id'

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :addresses, presence: true


def address_display
  '〒' + postal_code + '' + addresses + '' + name
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
  
  
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer, foreign_key: 'customer_id'
  belongs_to :item, foreign_key: 'item_id'

  validates :item_id, presence: true
  validates :customer_id, presence: true
  validates :amount, presence: true



  def add_tax_price_cart
        (item.price * 1.1).round
  end

  def subtotal
    add_tax_price_cart * amount
  end






end

app/models/customer.rb
class Customer < ApplicationRecord



  has_many :cart_items
  has_many :orders
  has_many :addresses

  with_options presence: true do

    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :email
    validates :postal_code
    validates :address
    validates :telephone_number


  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



def address_display_customer
  '〒' + self.postal_code + '' + self.address + '' + self.last_name + '' + self.first_name
end

def full_name
      self.last_name + self.first_name
end

def full_name_kana
  self.last_name_kana + self.first_name_kana
end




end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, foreign_key: 'genre_id'
  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre, foreign_key: 'genre_id'
  has_many :cart_items
  has_many :order_details

 with_options presence: true do

     validates :name
     validates :introduction
     validates :price


   end



  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def add_tax_price
        (self.price * 1.1).round
  end


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, foreign_key: 'customer_id'
  has_many :order_details


  enum payment: { credit_card: 0, transfer: 1}
  enum status: { wait: 0, confirmation: 1, production: 2, shipment: 3, complete: 4}

   with_options presence: true do
     validates :customer_id
     validates :billing_amount
     validates :postage
     validates :delivery_postal_code
     validates :delivery_address
     validates :delivery_name
     validates :payment
     validates :status

   end

def address_display_order
    '〒' + delivery_postal_code.to_s + ' ' + delivery_address + ' ' + delivery_name
end


def postage
    800
end

def price_total
  self.purchase_price * self.amount
end

def order_total
   self.billing_amount + postage
end




end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item, foreign_key: 'item_id'

  enum making_status: { no_making: 0, wait: 1, production: 2, complete: 3}


def price_total
  self.purchase_price * self.amount
end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!, except: [:top]

  def top
    @orders = Order.all

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController



  def index
    @items = Item.all
    @genre = Genre.all



  end

  def new
    @item = Item.new
    @genre = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to action: "show", id: @item
    else
     @item = Item.new
     @genre = Genre.all
     render action: "new"

    end

  end

  def show
    @item = Item.find(params[:id])

  end

  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
  end





  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to action: "show"
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id)

  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

before_action :authenticate_admin!

def show
  @order = Order.find(params[:id])
  @order_details = @order.order_details.pluck(:making_status)
  if @order.status == "shipment"
  elsif @order.status == "complete"
  else

   if @order_details.all? { |d| d == "complete"}
     @order.status = "shipment"
     @order.update(order_params)
   end
  end
end

def update
   @order = Order.find(params[:id])
   @order.update(order_params)

    if @order.status == "confirmation"
     @order_details = @order.order_details
     @order_details.each do |detail|
       detail.making_status = 1
       detail.update(order_detail_params)
      end
    end
    redirect_to action: "show"

end

private

  def order_params
    params.permit(:payment, :delivery_address, :delivery_postal_code,:delivery_name, :postage, :billing_amount, :status)
  end

  def order_detail_params
    params.permit(:purchase_price, :amount, :item_id, :order_id,)
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


 before_action :configure_permitted_parameters, if: :devise_controller?


 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
     new_admin_session_path
    else
     root_path
    end
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all

  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to action: "index"
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to action: "index"

  end

  def destroy
  end



  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end

  def about
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/orders/show.html.erb
<div class="container">

  <div class="row">

    <div class="col-6">
    <h2 class="mt-5 ml-5">注文履歴詳細</h2>
    <table class="table table-borderless">
      <tr><th>購入者</th><td><%= @order.customer.full_name %></td></tr>
      <tr><th>注文日</th><td><%= @order.created_at.strftime("%Y/%m/%d") %></td></tr>
      <tr><th>配送先</th><td><%= @order.address_display_order %></td></tr>
      <tr><th>支払方法</th><td><%= @order.payment_i18n %></td></tr>
      <tr>
        <th>注文ステータス</th>
        <td>
          <%= form_with url: admin_order_path, method: :patch, local: true do |f| %>
          <%= f.select :status, Order.statuses.keys.map { |k|  [I18n.t("enums.order.status.#{k}"),k]}, { selected: @order.status} %>
          <%= f.submit "更新", class:"btn btn-success" %>
        </td>
        <td>

        </td>
        <% end %>
      </tr>
    </table>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <table class="table">
      <thead>
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @order.order_details.each do |d| %>
        <tr>
         <td><%= d.item.name %></td>
         <td><%= d.purchase_price.to_s(:delimited) %></td>
         <td><%= d.amount %></td>
         <td><%= d.price_total.to_s(:delimited) %></td>
         <td>
           <%= form_with url: admin_order_detail_path(d), method: :patch, local: true do |f| %>
           <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |k| [I18n.t("enums.order_detail.making_status.#{k}"),k]}, { selected: d.making_status} %>

           <%= f.submit "更新", class:"btn btn-success" %>
           <% end %>
         <td></td>
        </tr>

        <% end %>
      </tbody>
    </table>
    </div>
    <div class="col-4 ml-3">
        <table class="table table-borderless align-items-end">
          <tr><th>商品合計</th><td><%= @order.billing_amount.to_s(:delimited) %>円</td></tr>
          <tr><th>送料</th><td><%= @order.postage %>円</td></tr>
          <tr><th>請求合計金額</th><td><%= @order.order_total.to_s(:delimited) %>円</td></tr>
        </table>
    </div>
  </div>
</div>