config/routes.rb
Rails.application.routes.draw do

namespace :admin do
   resources :items
   resources :customers
   root to: "homes#top"
   resources :orders, only: [:show, :update]
   resources :genres
   resources :order_details, only: [:update]
  end


  devise_for :customers, skip: [:passwords] ,controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'

  }

  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

resources :items, only: [:show, :index], controller: "public/items"
resources :addresses, controller: "public/addresses"
resources :orders, controller: "public/orders" do
  collection do
    post 'confirm'
    get 'complete'
  end
end
resources :cart_items, controller: "public/cart_items" do
  collection do
    delete 'destroy_all'
  end
end

resource :customers, except: [:show], controller: "public/customers" do
  collection do
    get 'unsubscribe'
    get 'my_page' => "public/customers#show"
    patch "withdraw"
  end
end

get "about" => "public/homes#about"


  root to: "public/homes#top"






  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer, foreign_key: 'customer_id'

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :addresses, presence: true


def address_display
  '〒' + postal_code + '' + addresses + '' + name
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
  
  
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer, foreign_key: 'customer_id'
  belongs_to :item, foreign_key: 'item_id'

  validates :item_id, presence: true
  validates :customer_id, presence: true
  validates :amount, presence: true



  def add_tax_price_cart
        (item.price * 1.1).round
  end

  def subtotal
    add_tax_price_cart * amount
  end






end

app/models/customer.rb
class Customer < ApplicationRecord



  has_many :cart_items
  has_many :orders
  has_many :addresses

  with_options presence: true do

    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :email
    validates :postal_code
    validates :address
    validates :telephone_number


  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



def address_display_customer
  '〒' + self.postal_code + '' + self.address + '' + self.last_name + '' + self.first_name
end

def full_name
      self.last_name + self.first_name
end

def full_name_kana
  self.last_name_kana + self.first_name_kana
end




end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, foreign_key: 'genre_id'
  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre, foreign_key: 'genre_id'
  has_many :cart_items
  has_many :order_details

 with_options presence: true do

     validates :name
     validates :introduction
     validates :price


   end



  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def add_tax_price
        (self.price * 1.1).round
  end


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, foreign_key: 'customer_id'
  has_many :order_details


  enum payment: { credit_card: 0, transfer: 1}
  enum status: { wait: 0, confirmation: 1, production: 2, shipment: 3, complete: 4}

   with_options presence: true do
     validates :customer_id
     validates :billing_amount
     validates :postage
     validates :delivery_postal_code
     validates :delivery_address
     validates :delivery_name
     validates :payment
     validates :status

   end

def address_display_order
    '〒' + delivery_postal_code.to_s + ' ' + delivery_address + ' ' + delivery_name
end


def postage
    800
end

def price_total
  self.purchase_price * self.amount
end

def order_total
   self.billing_amount + postage
end




end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item, foreign_key: 'item_id'

  enum making_status: { no_making: 0, wait: 1, production: 2, complete: 3}


def price_total
  self.purchase_price * self.amount
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


 before_action :configure_permitted_parameters, if: :devise_controller?


 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
     new_admin_session_path
    else
     root_path
    end
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all

  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to action: "index"
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to action: "index"

  end

  def destroy
  end



  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end

  def about
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/9c2b7fd351.js" crossorigin="anonymous"></script>

  </head>

  <body>
    <header>
      <div class="container mt-5">
       <div class="row">

        <div><%= image_tag 'logo.png' %></div>

        <% if customer_signed_in? %>
        <div class="col text-right">
         <%= link_to "マイページ", my_page_customers_path, class:"btn btn-light" %>
         <%= link_to "商品一覧", items_path, class:"btn btn-light" %>
         <%= link_to "カート", cart_items_path, class:"btn btn-light"%>
         <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"btn btn-light" %>
         <p class="mt-2">ようこそ<span class="mr-1 ml-1"><%= current_customer.full_name %></span>さん</p>
        </div>
        <% elsif admin_signed_in? %>
        <div class="col text-right">
         <%= link_to "商品一覧", admin_items_path, class:"btn btn-light" %>
         <%= link_to "会員一覧", admin_customers_path, class:"btn btn-light" %>
         <%= link_to "注文履歴一覧", admin_root_path, class:"btn btn-light" %>
         <%= link_to "ジャンル一覧", admin_genres_path, class:"btn btn-light" %>
         <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"btn btn-light" %>
        </div>
        <% else %>
        <div class="col text-right">
         <%= link_to "About", about_path, class:"btn btn-light" %>
         <%= link_to "商品一覧", items_path, class:"btn btn-light" %>
         <%= link_to "新規登録", new_customer_registration_path, class:"btn btn-light" %>
         <%= link_to "ログイン", customer_session_path, class:"btn btn-light"  %>
        </div>
        <% end %>


        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>